import { Inter } from "next/font/google";
import "./globals.css";
import Dashboard from "@/components/Dashboard";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Copy Paste",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex justify-center my-2 mx-2">
          <Dashboard />
        </div>
        {children}
      </body>
    </html>
  );
}
